config/routes.rb
PomoCount::Application.routes.draw do
  resources :entries

  devise_for :users do
    match '/user' => 'devise/registrations#edit',:as => :user_root
  end

  root :to => 'static_pages#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  before_validation :set_default_values

  belongs_to :user

  private

    def set_default_values
      self.length    ||= 25
      self.timestamp ||= Time.now
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = current_user.entries
  end

  def edit
  end

  def new
    @entry = Entry.new :user => current_user
  end

  def create
    @entry = Entry.new params[:entry].merge(:user_id => current_user.id)
    if @entry.save
      redirect_to entries_path
    else
      render :action => :new
    end
  end

  def update
  end

  def destroy
    @entry = current_user.entries.find params[:id]

    if @entry.destroy
      flash[:success] = 'Entry removed'
    else
      flash[:error] = 'Could not remove that entry. Try again.'
    end

    redirect_to entries_path
  end

  def show
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
      when :alert
        'warning'
      when :error
        'error'
      when :notice
        'info'
      when :success
        'success'
      else
        type.to_s
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.erb
<h1>Entries#edit</h1>
<p>Find me in app/views/entries/edit.html.erb</p>

app/views/entries/index.html.erb
<h1>Pomodoro Entries</h1>

<p><%= link_to 'New entry', new_entry_path, :class => 'btn success' %></p>

<% if @entries.present? %>
  <table>
  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.timestamp %></td>
      <td><%= entry.length %></td>
      <td><%= link_to 'Delete', entry_path(entry), :class => 'btn danger', :method => 'delete', :confirm => 'Are you sure?' %></td>
    </tr>
  <% end -%>
  </table>
<% else -%>
  <p>You have no Pomodoro entries</p>
<% end -%>

app/views/entries/new.html.erb
<h1>New Pomodoro entry</h1>

<%= semantic_form_for @entry do |form| %>
  <%= form.input :timestamp, :as => :string %>
  <%= form.input :length %>
  <%= form.submit %>
<% end -%>

app/views/entries/show.html.erb
<h1>Entries#show</h1>
<p>Find me in app/views/entries/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>PomoCount</title>
    <meta name="description" content="">
    <meta name="author" content="">

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link href="../bootstrap.css" rel="stylesheet">
    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .container > .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }

    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Project name</a>
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <% if user_signed_in? -%>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
            <% else -%>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Join Now', new_user_registration_path %></li>
            <% end -%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="page-header">
          <h1>Page name <small>Supporting text or tagline</small></h1>
        </div>
        <div class="row">
          <div class="span10">
            <% flash.each do |type, message| %>
              <div class="alert-message fade in <%= twitterized_type(type) %>" data-alert="alert">
                <a class="close" href="#">×</a>
                <p><%= message %></p>
              </div>
            <% end -%>

            <% if current_user %>
              <p>Hi <%= current_user.email %></p>
            <% end -%>

            <%= yield %>
          </div>
          <div class="span4">
            <h3>Secondary content</h3>
          </div>
        </div>
      </div>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>